package com.sugar.chat.pojo;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

public final class ChatMessage {
  private ChatMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MsgActionEnum}
   */
  public enum MsgActionEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *(1, "第一次(或重连)初始化连接"),
     * </pre>
     *
     * <code>CONNECT = 0;</code>
     */
    CONNECT(0),
    /**
     * <pre>
     *(2, "聊天消息"),
     * </pre>
     *
     * <code>CHAT = 1;</code>
     */
    CHAT(1),
    /**
     * <pre>
     *(3, "消息签收"),
     * </pre>
     *
     * <code>SIGNED = 2;</code>
     */
    SIGNED(2),
    /**
     * <pre>
     *KEEPALIVE(4, "客户端保持心跳"),
     * </pre>
     *
     * <code>PULL_FRIEND = 3;</code>
     */
    PULL_FRIEND(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *(1, "第一次(或重连)初始化连接"),
     * </pre>
     *
     * <code>CONNECT = 0;</code>
     */
    public static final int CONNECT_VALUE = 0;
    /**
     * <pre>
     *(2, "聊天消息"),
     * </pre>
     *
     * <code>CHAT = 1;</code>
     */
    public static final int CHAT_VALUE = 1;
    /**
     * <pre>
     *(3, "消息签收"),
     * </pre>
     *
     * <code>SIGNED = 2;</code>
     */
    public static final int SIGNED_VALUE = 2;
    /**
     * <pre>
     *KEEPALIVE(4, "客户端保持心跳"),
     * </pre>
     *
     * <code>PULL_FRIEND = 3;</code>
     */
    public static final int PULL_FRIEND_VALUE = 3;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MsgActionEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgActionEnum forNumber(int value) {
      switch (value) {
        case 0: return CONNECT;
        case 1: return CHAT;
        case 2: return SIGNED;
        case 3: return PULL_FRIEND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgActionEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgActionEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgActionEnum>() {
            @Override
            public MsgActionEnum findValueByNumber(int number) {
              return MsgActionEnum.forNumber(number);
            }
          };

    @Override
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    @Override
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ChatMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgActionEnum[] VALUES = values();

    public static MsgActionEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgActionEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MsgActionEnum)
  }

  /**
   * Protobuf enum {@code RouteMsgActionEnum}
   */
  public enum RouteMsgActionEnum
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SHUTDOWN_USER = 0;</code>
     */
    SHUTDOWN_USER(0),
    /**
     * <code>REGISTER = 1;</code>
     */
    REGISTER(1),
    /**
     * <code>PUSH_ALL_USER_MESSAGE = 2;</code>
     */
    PUSH_ALL_USER_MESSAGE(2),
    /**
     * <code>ALL_USER = 3;</code>
     */
    ALL_USER(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SHUTDOWN_USER = 0;</code>
     */
    public static final int SHUTDOWN_USER_VALUE = 0;
    /**
     * <code>REGISTER = 1;</code>
     */
    public static final int REGISTER_VALUE = 1;
    /**
     * <code>PUSH_ALL_USER_MESSAGE = 2;</code>
     */
    public static final int PUSH_ALL_USER_MESSAGE_VALUE = 2;
    /**
     * <code>ALL_USER = 3;</code>
     */
    public static final int ALL_USER_VALUE = 3;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RouteMsgActionEnum valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static RouteMsgActionEnum forNumber(int value) {
      switch (value) {
        case 0: return SHUTDOWN_USER;
        case 1: return REGISTER;
        case 2: return PUSH_ALL_USER_MESSAGE;
        case 3: return ALL_USER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RouteMsgActionEnum>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RouteMsgActionEnum> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RouteMsgActionEnum>() {
            @Override
            public RouteMsgActionEnum findValueByNumber(int number) {
              return RouteMsgActionEnum.forNumber(number);
            }
          };

    @Override
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    @Override
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ChatMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final RouteMsgActionEnum[] VALUES = values();

    public static RouteMsgActionEnum valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RouteMsgActionEnum(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RouteMsgActionEnum)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Message.DataType dataType = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    int getDataTypeValue();
    /**
     * <code>.Message.DataType dataType = 1;</code>
     * @return The dataType.
     */
    Message.DataType getDataType();

    /**
     * <code>.ChatMsg chatMsg = 2;</code>
     * @return Whether the chatMsg field is set.
     */
    boolean hasChatMsg();
    /**
     * <code>.ChatMsg chatMsg = 2;</code>
     * @return The chatMsg.
     */
    ChatMsg getChatMsg();
    /**
     * <code>.ChatMsg chatMsg = 2;</code>
     */
    ChatMsgOrBuilder getChatMsgOrBuilder();

    /**
     * <code>.RouteMsg RouteMsg = 3;</code>
     * @return Whether the routeMsg field is set.
     */
    boolean hasRouteMsg();
    /**
     * <code>.RouteMsg RouteMsg = 3;</code>
     * @return The routeMsg.
     */
    RouteMsg getRouteMsg();
    /**
     * <code>.RouteMsg RouteMsg = 3;</code>
     */
    RouteMsgOrBuilder getRouteMsgOrBuilder();

    public Message.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      dataType_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              ChatMsg.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((ChatMsg) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(ChatMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ChatMsg) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              RouteMsg.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((RouteMsg) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(RouteMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((RouteMsg) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChatMessage.internal_static_Message_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChatMessage.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    /**
     * Protobuf enum {@code Message.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ChatMsgType = 0;</code>
       */
      ChatMsgType(0),
      /**
       * <code>RouteMsgType = 1;</code>
       */
      RouteMsgType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ChatMsgType = 0;</code>
       */
      public static final int ChatMsgType_VALUE = 0;
      /**
       * <code>RouteMsgType = 1;</code>
       */
      public static final int RouteMsgType_VALUE = 1;


      @Override
      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return ChatMsgType;
          case 1: return RouteMsgType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              @Override
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      @Override
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      @Override
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.DataType)
    }

    private int dataBodyCase_ = 0;
    private Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      CHATMSG(2),
      ROUTEMSG(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return CHATMSG;
          case 3: return ROUTEMSG;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      @Override
      public int getNumber() {
        return this.value;
      }
    };

    @Override
    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATATYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <code>.Message.DataType dataType = 1;</code>
     * @return The enum numeric value on the wire for dataType.
     */
    @Override public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <code>.Message.DataType dataType = 1;</code>
     * @return The dataType.
     */
    @Override public DataType getDataType() {
      @SuppressWarnings("deprecation")
      DataType result = DataType.valueOf(dataType_);
      return result == null ? DataType.UNRECOGNIZED : result;
    }

    public static final int CHATMSG_FIELD_NUMBER = 2;
    /**
     * <code>.ChatMsg chatMsg = 2;</code>
     * @return Whether the chatMsg field is set.
     */
    @Override
    public boolean hasChatMsg() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.ChatMsg chatMsg = 2;</code>
     * @return The chatMsg.
     */
    @Override
    public ChatMsg getChatMsg() {
      if (dataBodyCase_ == 2) {
         return (ChatMsg) dataBody_;
      }
      return ChatMsg.getDefaultInstance();
    }
    /**
     * <code>.ChatMsg chatMsg = 2;</code>
     */
    @Override
    public ChatMsgOrBuilder getChatMsgOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (ChatMsg) dataBody_;
      }
      return ChatMsg.getDefaultInstance();
    }

    public static final int ROUTEMSG_FIELD_NUMBER = 3;
    /**
     * <code>.RouteMsg RouteMsg = 3;</code>
     * @return Whether the routeMsg field is set.
     */
    @Override
    public boolean hasRouteMsg() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.RouteMsg RouteMsg = 3;</code>
     * @return The routeMsg.
     */
    @Override
    public RouteMsg getRouteMsg() {
      if (dataBodyCase_ == 3) {
         return (RouteMsg) dataBody_;
      }
      return RouteMsg.getDefaultInstance();
    }
    /**
     * <code>.RouteMsg RouteMsg = 3;</code>
     */
    @Override
    public RouteMsgOrBuilder getRouteMsgOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (RouteMsg) dataBody_;
      }
      return RouteMsg.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != DataType.ChatMsgType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (ChatMsg) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (RouteMsg) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if (dataType_ != DataType.ChatMsgType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ChatMsg) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (RouteMsg) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message)) {
        return super.equals(obj);
      }
      Message other = (Message) obj;

      if (dataType_ != other.dataType_) {
        return false;
      }
      if (!getDataBodyCase().equals(other.getDataBodyCase())) {
        return false;
      }
      switch (dataBodyCase_) {
        case 2:
          if (!getChatMsg()
              .equals(other.getChatMsg())) {
            return false;
          }
          break;
        case 3:
          if (!getRouteMsg()
              .equals(other.getRouteMsg())) {
            return false;
          }
          break;
        case 0:
        default:
      }
      return unknownFields.equals(other.unknownFields);
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + CHATMSG_FIELD_NUMBER;
          hash = (53 * hash) + getChatMsg().hashCode();
          break;
        case 3:
          hash = (37 * hash) + ROUTEMSG_FIELD_NUMBER;
          hash = (53 * hash) + getRouteMsg().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChatMessage.internal_static_Message_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChatMessage.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using ChatMessage.Message.newBuilder()
      public Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChatMessage.internal_static_Message_descriptor;
      }

      @Override
      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      @Override
      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Message buildPartial() {
        Message result = new Message(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (chatMsgBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = chatMsgBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (routeMsgBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = routeMsgBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) {
          return this;
        }
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case CHATMSG: {
            mergeChatMsg(other.getChatMsg());
            break;
          }
          case ROUTEMSG: {
            mergeRouteMsg(other.getRouteMsg());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private Object dataBody_;
      @Override
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <code>.Message.DataType dataType = 1;</code>
       * @return The enum numeric value on the wire for dataType.
       */
      @Override public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <code>.Message.DataType dataType = 1;</code>
       * @param value The enum numeric value on the wire for dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataTypeValue(int value) {
        
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Message.DataType dataType = 1;</code>
       * @return The dataType.
       */
      @Override
      public DataType getDataType() {
        @SuppressWarnings("deprecation")
        DataType result = DataType.valueOf(dataType_);
        return result == null ? DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Message.DataType dataType = 1;</code>
       * @param value The dataType to set.
       * @return This builder for chaining.
       */
      public Builder setDataType(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Message.DataType dataType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ChatMsg, ChatMsg.Builder, ChatMsgOrBuilder> chatMsgBuilder_;
      /**
       * <code>.ChatMsg chatMsg = 2;</code>
       * @return Whether the chatMsg field is set.
       */
      @Override
      public boolean hasChatMsg() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.ChatMsg chatMsg = 2;</code>
       * @return The chatMsg.
       */
      @Override
      public ChatMsg getChatMsg() {
        if (chatMsgBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (ChatMsg) dataBody_;
          }
          return ChatMsg.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return chatMsgBuilder_.getMessage();
          }
          return ChatMsg.getDefaultInstance();
        }
      }
      /**
       * <code>.ChatMsg chatMsg = 2;</code>
       */
      public Builder setChatMsg(ChatMsg value) {
        if (chatMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          chatMsgBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ChatMsg chatMsg = 2;</code>
       */
      public Builder setChatMsg(
          ChatMsg.Builder builderForValue) {
        if (chatMsgBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          chatMsgBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ChatMsg chatMsg = 2;</code>
       */
      public Builder mergeChatMsg(ChatMsg value) {
        if (chatMsgBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != ChatMsg.getDefaultInstance()) {
            dataBody_ = ChatMsg.newBuilder((ChatMsg) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            chatMsgBuilder_.mergeFrom(value);
          }
          chatMsgBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.ChatMsg chatMsg = 2;</code>
       */
      public Builder clearChatMsg() {
        if (chatMsgBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          chatMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ChatMsg chatMsg = 2;</code>
       */
      public ChatMsg.Builder getChatMsgBuilder() {
        return getChatMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.ChatMsg chatMsg = 2;</code>
       */
      @Override
      public ChatMsgOrBuilder getChatMsgOrBuilder() {
        if ((dataBodyCase_ == 2) && (chatMsgBuilder_ != null)) {
          return chatMsgBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (ChatMsg) dataBody_;
          }
          return ChatMsg.getDefaultInstance();
        }
      }
      /**
       * <code>.ChatMsg chatMsg = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ChatMsg, ChatMsg.Builder, ChatMsgOrBuilder>
          getChatMsgFieldBuilder() {
        if (chatMsgBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = ChatMsg.getDefaultInstance();
          }
          chatMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ChatMsg, ChatMsg.Builder, ChatMsgOrBuilder>(
                  (ChatMsg) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return chatMsgBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          RouteMsg, RouteMsg.Builder, RouteMsgOrBuilder> routeMsgBuilder_;
      /**
       * <code>.RouteMsg RouteMsg = 3;</code>
       * @return Whether the routeMsg field is set.
       */
      @Override
      public boolean hasRouteMsg() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.RouteMsg RouteMsg = 3;</code>
       * @return The routeMsg.
       */
      @Override
      public RouteMsg getRouteMsg() {
        if (routeMsgBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (RouteMsg) dataBody_;
          }
          return RouteMsg.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return routeMsgBuilder_.getMessage();
          }
          return RouteMsg.getDefaultInstance();
        }
      }
      /**
       * <code>.RouteMsg RouteMsg = 3;</code>
       */
      public Builder setRouteMsg(RouteMsg value) {
        if (routeMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          routeMsgBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.RouteMsg RouteMsg = 3;</code>
       */
      public Builder setRouteMsg(
          RouteMsg.Builder builderForValue) {
        if (routeMsgBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          routeMsgBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.RouteMsg RouteMsg = 3;</code>
       */
      public Builder mergeRouteMsg(RouteMsg value) {
        if (routeMsgBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != RouteMsg.getDefaultInstance()) {
            dataBody_ = RouteMsg.newBuilder((RouteMsg) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            routeMsgBuilder_.mergeFrom(value);
          }
          routeMsgBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.RouteMsg RouteMsg = 3;</code>
       */
      public Builder clearRouteMsg() {
        if (routeMsgBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          routeMsgBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.RouteMsg RouteMsg = 3;</code>
       */
      public RouteMsg.Builder getRouteMsgBuilder() {
        return getRouteMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.RouteMsg RouteMsg = 3;</code>
       */
      @Override
      public RouteMsgOrBuilder getRouteMsgOrBuilder() {
        if ((dataBodyCase_ == 3) && (routeMsgBuilder_ != null)) {
          return routeMsgBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (RouteMsg) dataBody_;
          }
          return RouteMsg.getDefaultInstance();
        }
      }
      /**
       * <code>.RouteMsg RouteMsg = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          RouteMsg, RouteMsg.Builder, RouteMsgOrBuilder>
          getRouteMsgFieldBuilder() {
        if (routeMsgBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = RouteMsg.getDefaultInstance();
          }
          routeMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              RouteMsg, RouteMsg.Builder, RouteMsgOrBuilder>(
                  (RouteMsg) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return routeMsgBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
    }

    public static Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @Override
    public Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ChatMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChatMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.MsgActionEnum msgAction = 1;</code>
     * @return The enum numeric value on the wire for msgAction.
     */
    int getMsgActionValue();
    /**
     * <code>.MsgActionEnum msgAction = 1;</code>
     * @return The msgAction.
     */
    MsgActionEnum getMsgAction();

    /**
     * <code>string userId = 2;</code>
     * @return The userId.
     */
    String getUserId();
    /**
     * <code>string userId = 2;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>string toUserId = 3;</code>
     * @return The toUserId.
     */
    String getToUserId();
    /**
     * <code>string toUserId = 3;</code>
     * @return The bytes for toUserId.
     */
    com.google.protobuf.ByteString
        getToUserIdBytes();

    /**
     * <code>string data = 4;</code>
     * @return The data.
     */
    String getData();
    /**
     * <code>string data = 4;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code ChatMsg}
   */
  public static final class ChatMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ChatMsg)
      ChatMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMsg.newBuilder() to construct.
    private ChatMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMsg() {
      msgAction_ = 0;
      userId_ = "";
      toUserId_ = "";
      data_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              msgAction_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              toUserId_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChatMessage.internal_static_ChatMsg_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChatMessage.internal_static_ChatMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatMsg.class, Builder.class);
    }

    public static final int MSGACTION_FIELD_NUMBER = 1;
    private int msgAction_;
    /**
     * <code>.MsgActionEnum msgAction = 1;</code>
     * @return The enum numeric value on the wire for msgAction.
     */
    @Override public int getMsgActionValue() {
      return msgAction_;
    }
    /**
     * <code>.MsgActionEnum msgAction = 1;</code>
     * @return The msgAction.
     */
    @Override public MsgActionEnum getMsgAction() {
      @SuppressWarnings("deprecation")
      MsgActionEnum result = MsgActionEnum.valueOf(msgAction_);
      return result == null ? MsgActionEnum.UNRECOGNIZED : result;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private volatile Object userId_;
    /**
     * <code>string userId = 2;</code>
     * @return The userId.
     */
    @Override
    public String getUserId() {
      Object ref = userId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string userId = 2;</code>
     * @return The bytes for userId.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOUSERID_FIELD_NUMBER = 3;
    private volatile Object toUserId_;
    /**
     * <code>string toUserId = 3;</code>
     * @return The toUserId.
     */
    @Override
    public String getToUserId() {
      Object ref = toUserId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        toUserId_ = s;
        return s;
      }
    }
    /**
     * <code>string toUserId = 3;</code>
     * @return The bytes for toUserId.
     */
    @Override
    public com.google.protobuf.ByteString
        getToUserIdBytes() {
      Object ref = toUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        toUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private volatile Object data_;
    /**
     * <code>string data = 4;</code>
     * @return The data.
     */
    @Override
    public String getData() {
      Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 4;</code>
     * @return The bytes for data.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgAction_ != MsgActionEnum.CONNECT.getNumber()) {
        output.writeEnum(1, msgAction_);
      }
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
      }
      if (!getToUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, toUserId_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, data_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if (msgAction_ != MsgActionEnum.CONNECT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgAction_);
      }
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
      }
      if (!getToUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, toUserId_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChatMsg)) {
        return super.equals(obj);
      }
      ChatMsg other = (ChatMsg) obj;

      if (msgAction_ != other.msgAction_) {
        return false;
      }
      if (!getUserId()
          .equals(other.getUserId())) {
        return false;
      }
      if (!getToUserId()
          .equals(other.getToUserId())) {
        return false;
      }
      if (!getData()
          .equals(other.getData())) {
        return false;
      }
      if (!unknownFields.equals(other.unknownFields)) {
        return false;
      }
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGACTION_FIELD_NUMBER;
      hash = (53 * hash) + msgAction_;
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      hash = (37 * hash) + TOUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getToUserId().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChatMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ChatMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ChatMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChatMsg)
        ChatMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChatMessage.internal_static_ChatMsg_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChatMessage.internal_static_ChatMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChatMsg.class, Builder.class);
      }

      // Construct using ChatMessage.ChatMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgAction_ = 0;

        userId_ = "";

        toUserId_ = "";

        data_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChatMessage.internal_static_ChatMsg_descriptor;
      }

      @Override
      public ChatMsg getDefaultInstanceForType() {
        return ChatMsg.getDefaultInstance();
      }

      @Override
      public ChatMsg build() {
        ChatMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ChatMsg buildPartial() {
        ChatMsg result = new ChatMsg(this);
        result.msgAction_ = msgAction_;
        result.userId_ = userId_;
        result.toUserId_ = toUserId_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChatMsg) {
          return mergeFrom((ChatMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChatMsg other) {
        if (other == ChatMsg.getDefaultInstance()) {
          return this;
        }
        if (other.msgAction_ != 0) {
          setMsgActionValue(other.getMsgActionValue());
        }
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getToUserId().isEmpty()) {
          toUserId_ = other.toUserId_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ChatMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ChatMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgAction_ = 0;
      /**
       * <code>.MsgActionEnum msgAction = 1;</code>
       * @return The enum numeric value on the wire for msgAction.
       */
      @Override public int getMsgActionValue() {
        return msgAction_;
      }
      /**
       * <code>.MsgActionEnum msgAction = 1;</code>
       * @param value The enum numeric value on the wire for msgAction to set.
       * @return This builder for chaining.
       */
      public Builder setMsgActionValue(int value) {
        
        msgAction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MsgActionEnum msgAction = 1;</code>
       * @return The msgAction.
       */
      @Override
      public MsgActionEnum getMsgAction() {
        @SuppressWarnings("deprecation")
        MsgActionEnum result = MsgActionEnum.valueOf(msgAction_);
        return result == null ? MsgActionEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.MsgActionEnum msgAction = 1;</code>
       * @param value The msgAction to set.
       * @return This builder for chaining.
       */
      public Builder setMsgAction(MsgActionEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgAction_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MsgActionEnum msgAction = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgAction() {
        
        msgAction_ = 0;
        onChanged();
        return this;
      }

      private Object userId_ = "";
      /**
       * <code>string userId = 2;</code>
       * @return The userId.
       */
      @Override
      public String getUserId() {
        Object ref = userId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string userId = 2;</code>
       * @return The bytes for userId.
       */
      @Override
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userId = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string userId = 2;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private Object toUserId_ = "";
      /**
       * <code>string toUserId = 3;</code>
       * @return The toUserId.
       */
      @Override
      public String getToUserId() {
        Object ref = toUserId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          toUserId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string toUserId = 3;</code>
       * @return The bytes for toUserId.
       */
      @Override
      public com.google.protobuf.ByteString
          getToUserIdBytes() {
        Object ref = toUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          toUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string toUserId = 3;</code>
       * @param value The toUserId to set.
       * @return This builder for chaining.
       */
      public Builder setToUserId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string toUserId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUserId() {
        
        toUserId_ = getDefaultInstance().getToUserId();
        onChanged();
        return this;
      }
      /**
       * <code>string toUserId = 3;</code>
       * @param value The bytes for toUserId to set.
       * @return This builder for chaining.
       */
      public Builder setToUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toUserId_ = value;
        onChanged();
        return this;
      }

      private Object data_ = "";
      /**
       * <code>string data = 4;</code>
       * @return The data.
       */
      @Override
      public String getData() {
        Object ref = data_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string data = 4;</code>
       * @return The bytes for data.
       */
      @Override
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 4;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 4;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ChatMsg)
    }

    // @@protoc_insertion_point(class_scope:ChatMsg)
    private static final ChatMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChatMsg();
    }

    public static ChatMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMsg>
        PARSER = new com.google.protobuf.AbstractParser<ChatMsg>() {
      @Override
      public ChatMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChatMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public ChatMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RouteMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RouteMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.RouteMsgActionEnum msgAction = 1;</code>
     * @return The enum numeric value on the wire for msgAction.
     */
    int getMsgActionValue();
    /**
     * <code>.RouteMsgActionEnum msgAction = 1;</code>
     * @return The msgAction.
     */
    RouteMsgActionEnum getMsgAction();

    /**
     * <code>string data = 2;</code>
     * @return The data.
     */
    String getData();
    /**
     * <code>string data = 2;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code RouteMsg}
   */
  public static final class RouteMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RouteMsg)
      RouteMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RouteMsg.newBuilder() to construct.
    private RouteMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RouteMsg() {
      msgAction_ = 0;
      data_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RouteMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RouteMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              msgAction_ = rawValue;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChatMessage.internal_static_RouteMsg_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChatMessage.internal_static_RouteMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RouteMsg.class, Builder.class);
    }

    public static final int MSGACTION_FIELD_NUMBER = 1;
    private int msgAction_;
    /**
     * <code>.RouteMsgActionEnum msgAction = 1;</code>
     * @return The enum numeric value on the wire for msgAction.
     */
    @Override public int getMsgActionValue() {
      return msgAction_;
    }
    /**
     * <code>.RouteMsgActionEnum msgAction = 1;</code>
     * @return The msgAction.
     */
    @Override public RouteMsgActionEnum getMsgAction() {
      @SuppressWarnings("deprecation")
      RouteMsgActionEnum result = RouteMsgActionEnum.valueOf(msgAction_);
      return result == null ? RouteMsgActionEnum.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private volatile Object data_;
    /**
     * <code>string data = 2;</code>
     * @return The data.
     */
    @Override
    public String getData() {
      Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 2;</code>
     * @return The bytes for data.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgAction_ != RouteMsgActionEnum.SHUTDOWN_USER.getNumber()) {
        output.writeEnum(1, msgAction_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, data_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if (msgAction_ != RouteMsgActionEnum.SHUTDOWN_USER.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, msgAction_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RouteMsg)) {
        return super.equals(obj);
      }
      RouteMsg other = (RouteMsg) obj;

      if (msgAction_ != other.msgAction_) {
        return false;
      }
      if (!getData()
          .equals(other.getData())) {
        return false;
      }
      if (!unknownFields.equals(other.unknownFields)) {
        return false;
      }
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGACTION_FIELD_NUMBER;
      hash = (53 * hash) + msgAction_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RouteMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RouteMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RouteMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RouteMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RouteMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RouteMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RouteMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RouteMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RouteMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RouteMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RouteMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RouteMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RouteMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RouteMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RouteMsg)
        RouteMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChatMessage.internal_static_RouteMsg_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChatMessage.internal_static_RouteMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RouteMsg.class, Builder.class);
      }

      // Construct using ChatMessage.RouteMsg.newBuilder()
      public Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgAction_ = 0;

        data_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChatMessage.internal_static_RouteMsg_descriptor;
      }

      @Override
      public RouteMsg getDefaultInstanceForType() {
        return RouteMsg.getDefaultInstance();
      }

      @Override
      public RouteMsg build() {
        RouteMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RouteMsg buildPartial() {
        RouteMsg result = new RouteMsg(this);
        result.msgAction_ = msgAction_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RouteMsg) {
          return mergeFrom((RouteMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RouteMsg other) {
        if (other == RouteMsg.getDefaultInstance()) {
          return this;
        }
        if (other.msgAction_ != 0) {
          setMsgActionValue(other.getMsgActionValue());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RouteMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RouteMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgAction_ = 0;
      /**
       * <code>.RouteMsgActionEnum msgAction = 1;</code>
       * @return The enum numeric value on the wire for msgAction.
       */
      @Override public int getMsgActionValue() {
        return msgAction_;
      }
      /**
       * <code>.RouteMsgActionEnum msgAction = 1;</code>
       * @param value The enum numeric value on the wire for msgAction to set.
       * @return This builder for chaining.
       */
      public Builder setMsgActionValue(int value) {
        
        msgAction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RouteMsgActionEnum msgAction = 1;</code>
       * @return The msgAction.
       */
      @Override
      public RouteMsgActionEnum getMsgAction() {
        @SuppressWarnings("deprecation")
        RouteMsgActionEnum result = RouteMsgActionEnum.valueOf(msgAction_);
        return result == null ? RouteMsgActionEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.RouteMsgActionEnum msgAction = 1;</code>
       * @param value The msgAction to set.
       * @return This builder for chaining.
       */
      public Builder setMsgAction(RouteMsgActionEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgAction_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RouteMsgActionEnum msgAction = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgAction() {
        
        msgAction_ = 0;
        onChanged();
        return this;
      }

      private Object data_ = "";
      /**
       * <code>string data = 2;</code>
       * @return The data.
       */
      @Override
      public String getData() {
        Object ref = data_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string data = 2;</code>
       * @return The bytes for data.
       */
      @Override
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 2;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 2;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RouteMsg)
    }

    // @@protoc_insertion_point(class_scope:RouteMsg)
    private static final RouteMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RouteMsg();
    }

    public static RouteMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RouteMsg>
        PARSER = new com.google.protobuf.AbstractParser<RouteMsg>() {
      @Override
      public RouteMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RouteMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RouteMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RouteMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public RouteMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChatMsg_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ChatMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RouteMsg_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RouteMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021ChatMessage.proto\"\245\001\n\007Message\022#\n\010dataT" +
      "ype\030\001 \001(\0162\021.Message.DataType\022\033\n\007chatMsg\030" +
      "\002 \001(\0132\010.ChatMsgH\000\022\035\n\010RouteMsg\030\003 \001(\0132\t.Ro" +
      "uteMsgH\000\"-\n\010DataType\022\017\n\013ChatMsgType\020\000\022\020\n" +
      "\014RouteMsgType\020\001B\n\n\010dataBody\"\\\n\007ChatMsg\022!" +
      "\n\tmsgAction\030\001 \001(\0162\016.MsgActionEnum\022\016\n\006use" +
      "rId\030\002 \001(\t\022\020\n\010toUserId\030\003 \001(\t\022\014\n\004data\030\004 \001(" +
      "\t\"@\n\010RouteMsg\022&\n\tmsgAction\030\001 \001(\0162\023.Route" +
      "MsgActionEnum\022\014\n\004data\030\002 \001(\t*C\n\rMsgAction" +
      "Enum\022\013\n\007CONNECT\020\000\022\010\n\004CHAT\020\001\022\n\n\006SIGNED\020\002\022" +
      "\017\n\013PULL_FRIEND\020\003*^\n\022RouteMsgActionEnum\022\021" +
      "\n\rSHUTDOWN_USER\020\000\022\014\n\010REGISTER\020\001\022\031\n\025PUSH_" +
      "ALL_USER_MESSAGE\020\002\022\014\n\010ALL_USER\020\003B\rB\013Chat" +
      "Messageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new String[] { "DataType", "ChatMsg", "RouteMsg", "DataBody", });
    internal_static_ChatMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ChatMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ChatMsg_descriptor,
        new String[] { "MsgAction", "UserId", "ToUserId", "Data", });
    internal_static_RouteMsg_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RouteMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RouteMsg_descriptor,
        new String[] { "MsgAction", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
